services:
  app-db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USE=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  queue-db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local